### ISSUE TITLE
header部分に CoderDojo のロゴを入れたい

### ISSUE THREAD

**Issue by kiriem** [coderdojo-japan/dojocon2018.coderdojo.jp#2]
![2018-03-23 22 31 21](https://user-images.githubusercontent.com/8245567/37831890-4ff1156a-2eea-11e8-8d23-d30925f8870b.png)

"DojoCon Japan 2018"の上あたりに白抜きされた CoderDojo ロゴが欲しいです！

**Comment by digitarhythm** [comment]
ロゴの画像ってどうすればいいですかね？

**Comment by digitarhythm** [comment]
とりあえずネットから拾ってきて作ってみた。
https://digitarhythm.github.io/dojocon2018.coderdojo.jp/

**Comment by kiriem** [comment]
https://coderdojo-kashiwa.com/event/spd/2017/image/dojo_logo_white.png
こちらの画像をお使いいただければと思います！

**Comment by digitarhythm** [comment]
見栄え的にはこんな感じでいいのかな？

**Comment by digitarhythm** [comment]
あ、アイコンだけなのね。
了解っす。

**Comment by digitarhythm** [comment]
こんな感じでどうでしょう。
https://digitarhythm.github.io/dojocon2018.coderdojo.jp/

**Comment by kiriem** [comment]
大変良きです！
サイズですが、今の半分にしてみていただけますか！

**Comment by digitarhythm** [comment]
そんな小さくてらイイのね(笑)
りょうかい！

**Comment by digitarhythm** [comment]
こんな感じ？
https://digitarhythm.github.io/dojocon2018.coderdojo.jp/

**Comment by kiriem** [comment]
とても良きです！
これでお願いします🙏

**Comment by digitarhythm** [comment]
pullリクだん。
