### ISSUE TITLE
１セッションに４人のプロフィールを掲載できるレイアウトが欲しい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojocon2018.coderdojo.jp#25]
@megane9988 セッション枠の中に ~~3人または4人~~ **4人** で登壇するパネルディスカッションの枠があるのですが、現在の [session レイアウト](https://github.com/coderdojo-japan/dojocon2018.coderdojo.jp/blob/master/_layouts/session.html)は１セッション1人の想定で作られていると思うので、１セッションに3人〜4人を掲載可能なレイアウトを作っていただけるととても嬉しいです...!! 🙏 ✨ 

cc/ @togazo @kawahara

**Comment by megane9988** [comment]
@yasulab  こちら、今の私の想像する実装方法だと、単純にスピーカーの変数を上側にどんどん足していって、それらを直接取り出すか、もしくはループで取り出す的なイメージをしていますが。実装としてはそんな感じであってますか？

なにかしら、サンプルとかあれば共有お願いします！
いまのままでも作れるは作れると思いますので、近日中に作りますね！

その場合OGPどうするか問題もちょっと悩ましいですね。別途スピーカー画像を一つにまとめた画像がいるかも

**Comment by yasulab** [comment]
> もしくはループで取り出す的なイメージをしていますが。実装としてはそんな感じであってますか？

@megane9988 そうですね! 😸 セッション側の状況としては、パネルディスカッションはモデレータ ( @togazo or @yasulab ) 情報も含めると４名で固定できるので、ループで取り出してもよいですが、まずはシンプルに４列固定のレイアウト作ってしまっても大丈夫そうです 🙆 

まずは４列固定で作ってしまって、時間があったらループで取り出すような形にリファクタリングするのはいかがでしょうか? 😸

**Comment by yasulab** [comment]
> その場合OGPどうするか問題もちょっと悩ましいですね。別途スピーカー画像を一つにまとめた画像がいるかも

@megane9988 こちらは悩ましいですね 🤔個人的にはご提案の通り、パネルディスカッションのレイアウトでは OGP 用のパラメータを別途新たに用意するのが楽そうかなと思いました 😊

**Comment by yasulab** [comment]
> OGP 用のパラメータを別途新たに用意するのが楽

具体的な実装案 (多分これでいけるはず?) は https://github.com/coderdojo-japan/dojocon2018.coderdojo.jp/issues/26#issuecomment-406761147 にまとめておきました ;)

**Comment by kawahara** [comment]
@megane9988 
こちら、セッション入力のついでにこちらでつくっちゃいまーす。

**Comment by togazo** [comment]
@yasulab @kawahara 既知と思いますが念のため。3人〜4人のくだりですが、4人ではなく全て3人で確定になったので宜しくお願いしますー（すでにフレキシブルなレイアウトにしているならスルーして下さい）

**Comment by yasulab** [comment]
こちらレイアウトが出来上がったので閉じちゃいますね ;) 実装ありがとうございました! 😆
https://dojocon2018.coderdojo.jp/session/1110_champions.html
