### ISSUE TITLE
セッションページの登壇者プロフィール画像を og:image に入れたい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojocon2018.coderdojo.jp#26]
現在は [_includes/header.html](https://github.com/coderdojo-japan/dojocon2018.coderdojo.jp/blob/master/_includes/header.html#L21) にある `og:image` がメインビジュアルで固定となっているので、セッションページのプロフィール画像のパラメータ (`thumbnail`) があれば `og:image` を上書きできるようにしたい 🤔💭

🤔.oO( @yasulab か @kawahara さんが PR を出して、 @megane9988 さんにレビューしてもらう形だと負担が減って良さそう...?)

**Comment by megane9988** [comment]
@yasulab 以下とかぶってます! 
https://github.com/coderdojo-japan/dojocon2018.coderdojo.jp/issues/19

ただ、こちらのほうが丁寧なので、向こう側をクローズしまーす！

**Comment by yasulab** [comment]
@megane9988 まだ試してないですが、多分こんな感じでいけるはず...? 🤔💭 cc/ @kawahara 

```jekyll
<meta property="og:image" content="{{ デフォルト値1 | デフォルト値2 | デフォルト値3 }}"/>
```

- デフォルト値1 = この値が `null` でなければ、この値が最も優先されて代入される
- デフォルト値2 = デフォルト値1が `null` なら、この値が次に優先されて代入される
- デフォルト値3 = デフォルト値1もデフォルト値2も `null` なら、この値が代入される
   - => この値を `mainvisual.png` とかにするイメージです 💭 

cf. https://github.com/oss-gate/oss-gate.github.io/blob/master/_includes/head.html

ご参考になれば幸いです! 😸

**Comment by megane9988** [comment]
@yasulab 

参考サイトを見る限り

`{{ デフォルト値1 | デフォルト値2 | デフォルト値3 }}`  この書き方は、第1の値をトリムしたり、何かを付与したりという処理をされてるっぽいような気がしました。

ので普通に条件分岐で実装しました。おかしかったら修正ください！ということで、このissueは開けときます。

**Comment by yasulab** [comment]
お、確かにその認識の方があっているっぽいですね 🤔
https://forestry.io/blog/what-s-new-in-jekyll-3-4-0/

もしかしたらもっと良い書き方もあるかもしれませんが、本題の Issue の方は解決できているので一先ず Issue は閉じちゃいますね ;) 
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fdojocon2018.coderdojo.jp%2Fsession%2Ftakashi-hosoya.html

早速のご対応ありがとうございました! 😸
