### ISSUE TITLE
footerの maintained by - を削除したい

### ISSUE THREAD

**Issue by kiriem** [coderdojo-japan/dojocon2018.coderdojo.jp#3]
DojoCon Japan は CoderDojo Japan のプロジェクトではないということを周知するためにも、この一文を削除しておきたいです😅
![2018-03-23 22 31 27](https://user-images.githubusercontent.com/8245567/37831966-8e43e9b4-2eea-11e8-9c02-45a6b3ec3381.png)

**Comment by digitarhythm** [comment]
修正してプルリクしました。
