### ISSUE TITLE
corectionで追加したものをループで呼び出す際の一覧表示おけるindex.htmlの除外方法

### ISSUE THREAD

**Issue by megane9988** [coderdojo-japan/dojocon2018.coderdojo.jp#30]
@yasulab  さん　もしくはjekyllに詳しいどなたか！

動的に更新コンテンツを扱えるように `session` を追加しました

https://github.com/coderdojo-japan/dojocon2018.coderdojo.jp/commit/93ef6d7717569bb89de3628aac52266bbf2606d7

そしてその中のものを一覧で表示します。

https://github.com/coderdojo-japan/dojocon2018.coderdojo.jp/commit/93ef6d7717569bb89de3628aac52266bbf2606d7#diff-e3b3b3686feaa1e1dfbd091152fbd84e

この場合にディレクトリにあるすべてのものが取得されてしまうため。一覧を表示するためだけにある `index.html` も含まれてしまい。うまくありません。

そこでループの中において

```
+        {% if session.layout == "archive" %}
+        {% else %}
```

というふうにして無理くりindex.htmlを除外したのですが。この時のうまいやり方があれば教えてください。

また今後増えたときにTOPでは、取得する数を制限したいので、その方法もどこか参考があれば教えてください！

お手数をお掛けします！

**Comment by megane9988** [comment]
https://genjiapp.com/blog/2013/11/17/jekyll-pagination.html

この辺を利用するのかなもしかしたら `{% for post in 2 %}` とかすると2件だけ取れたり。。試してから書きましょう。。

**Comment by megane9988** [comment]
`limit:4` という書き方を覚えました！ので件数はOKです。 indexの除外を教えてくださいませ！

**Comment by yasulab** [comment]
@megane9988 お、Webサイトを見た感じだと問題なく表示できてそうですが、こちら Close しちゃっても大丈夫ですかね? 👀 
https://dojocon2018.coderdojo.jp/#workshop

**Comment by yasulab** [comment]
とりあえず一旦 Close しちゃいますがもし問題あれば Re-open していただければ 😸 🙏
