### ISSUE TITLE
analyticsの導入

### ISSUE THREAD

**Issue by megane9988** [coderdojo-japan/dojocon2018.coderdojo.jp#35]
入れといたほうがなにかといいかもなのでちょっと遅いですが。アカウント取得とキーの共有をお願いします。

**Comment by yasulab** [comment]
@megane9988 どう共有するかはさておき、とりあえず一般社団法人 CoderDojo Japan のアカウントで発行した GA スクリプトで埋め込んでおきました! 🔧💨 cc/ @mjk0513 @champierre 
https://github.com/coderdojo-japan/dojocon2018.coderdojo.jp/commit/724dd146ebcf9c8a5bdda616ff4c4a983d4228f4
