### ISSUE TITLE
OGP設定をしたい

### ISSUE THREAD

**Issue by kiriem** [coderdojo-japan/dojocon2018.coderdojo.jp#6]
@kitakita048 
https://www.sakurasaku-labo.jp/blogs/facebook-og-image
を参考にしてOGP画像の作成をお願いしたい。

**Comment by kiriem** [comment]
@digitarhythm 北原が作成したOGP情報画像を元にOGP設定をお願いします🙇

**Comment by digitarhythm** [comment]
北原さんが作成したOGP情報画像はどこにあるのかな？

**Comment by kiriem** [comment]
OGPはまだできてません、29日には上げると言ってるのでそれ以降での対応でお願いします🙇

**Comment by digitarhythm** [comment]
これらの情報ってどこかにありますか？

- FacebookページのURI
- Twitterアカウント
- ページのdescription

**Comment by kiriem** [comment]
@digitarhythm Slackにも投げましたが、こちらでお願いできればと思います！

facebook : https://www.facebook.com/dojoconjapan/
twitter : https://twitter.com/DojoConJapan
description : DojoCon Japanは日本のCoderDojo関係者（見守る大人、学ぶ子供）とその活動に賛同・協賛する人が全国各地から集まる大きなイベントです。

**Comment by megane9988** [comment]
対応済です。
